Repository tue-robotics/tue-env, pull requests merged in 2019-02, with the labels that each got.

#359 Fix targets in CI
  Dockerfile
  installer/tue-install.bash
Labels: Test

#364 Fix returncode parsing
  installer/tue-install-impl.bash
Labels: in progress

#363 Install not often-used tooling on demand
  installer/tue-install-impl.bash
Labels: in progress

#360 SSH support
  installer/tue-install-impl.bash
  installer/tue-install.bash
  setup/tue-env-config.bash
  setup/tue-env.bash
  setup/tue-functions.bash
Labels: enhancement, in progress

#366 (tue-env)fix sourcing of env user-setup
  setup/tue-env-config.bash
  setup/tue-env.bash
Labels: in progress

#362 Add option to specify different sources per ROS distro
  README.md
  installer/parse-install-yaml.py
Labels: in progress

#370 Remove duplicate ssh functions
  setup/tue-functions.bash
Labels: in progress

#374 Let log be identical to output
  installer/tue-install-impl.bash
Labels: in progress
